
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pet_community?serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    type: com.alibaba.druid.pool.DruidDataSource
  #redis配置
#  redis:
    #redis服务器地址
#    host: 127.0.0.1
    #服务器连接端口
#    port: 6379
#    password: Ba1809Mncr..;
    #Redis数据库索引（默认0）
#    database: 0
    #连接超时时间（毫秒）=-   timeout: 1800000
#    lettuce:
#      pool:
        #连接池最大连接数
#        max-active: 20
        #最大阻塞等待时间（负数表示没限制
#        max-wait: -1
        #连接池中最大空闲连接
#        max-idle: 5
        #连接池中最小空闲连接
#        min-idle: 1
#mybatisplus日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml #扫描所有mybatis的xml文件
server:
  port: 9090